image_width: 720
image_height: 540
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [892.943991,    0.     ,  360.905728,
            0.     , 893.120511,  571.23168,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.237111, 0.266384, 0.001641, -0.001134, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1746.12952,    0.     ,  711.70852,    0.     ,
            0.     , 1767.90686,  572.7044 ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]