image_width: 720
image_height: 540
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [889.97948,   0.     , 350.2924 ,
           0.     , 889.94506, 282.79424,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.221250, 0.189576, -0.001343, 0.001121, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [859.53699,   0.     , 349.78499,   0.     ,
           0.     , 871.04034, 282.39279,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]