image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2409.11549,    0.     ,  687.93413,
            0.     , 2406.14303,  497.05181,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.133572, 0.597226, -0.002855, -0.003369, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2392.4353 ,    0.     ,  685.0793 ,    0.     ,
            0.     , 2390.98853,  495.17559,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]