/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 2500
    gain: 6.0

/serial_driver:
  ros__parameters:
    exposure_time_aim: 3800
    exposure_time_buff: 700
    gain_aim: 16.0
    gain_buff: 2.0
    timestamp_offset: 0.01
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 1
    binary_thres: 75

    light.min_ratio: 0.08
    armor.min_light_ratio: 0.5

    classifier_threshold: 0.6
    ignore_classes: ["negative"]

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz_max: 0.06
      sigma2_q_xyz_min: 0.03
      sigma2_q_yaw_max: 10.0
      sigma2_q_yaw_min: 5.0
      sigma2_q_r: 80.0
      r_xyz_factor: 5e-5
      r_yaw: 6e-3

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0
      tracking_thres: 3
      lost_time_thres: 0.5
      pitch_diff: 0.3
      yaw_diff: 1.2
      spinning_diff: 0.4
