/camera_node:
  ros__parameters:
    camera_info_url: package://rm_vision_bringup/config/camera_info.yaml
    exposure_time: 1000
    gain: 20.0

/serial_driver:
  ros__parameters:
    exposure_time_aim: 1000
    exposure_time_buff: 2000
    timestamp_offset: 0.01
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"

/armor_detector:
  ros__parameters:
    debug: true

    detect_color: 0

/armor_tracker:
  ros__parameters:
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_xyz: 0.08
      sigma2_q_yaw: 8
      sigma2_q_r: 80.0
      
      r_xyz_factor: 8e-5
      r_yaw: 9e-3
    
    ros_parameters:
      max_match_distance: 0.5
      max_match_yaw_diff: 1.0
      tracking_thres: 3
      lost_time_thres: 1.0
      pitch_diff: 0
      yaw_diff:  0
      spinning_diff: 0.2
