image_width: 540
image_height: 360
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1279.71168,    0.     ,  392.37896,
            0.     , 1269.967  ,  326.74877,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.229680, 0.253397, -0.000097, -0.001703, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1251.34033,    0.     ,  390.90397,    0.     ,
            0.     , 1251.88818,  326.81256,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]